#!/usr/bin/env python3
"""figures.py — published figures from results/summary/benchmark-long.csv.

Each figure's underlying data table is ALWAYS written as a CSV (so numbers are
available even before matplotlib is installed); the PNG is rendered only if
matplotlib is importable. Stdlib + optional matplotlib.

Figures:
  fig_throughput       prefill vs decode throughput per model (the bandwidth story)
  fig_energy_per_task  mean energy (J) per task per model/group
  fig_ttft             TTFT p50/p90/p99 per model
  fig_peak_memory      peak unified memory per model/group
  fig_success_energy   success/rubric vs energy Pareto (x=energy, y=quality)

KV-cache-vs-context needs per-sample raw data (vllm-metrics.csv); generated by
the dedicated raw reader if present (kv_vs_context), else skipped with a note.

Usage: figures.py [--long results/summary/benchmark-long.csv] [--out reports/charts]
"""
import argparse
import csv
import statistics
from collections import defaultdict
from pathlib import Path

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    HAVE_MPL = True
except Exception:
    HAVE_MPL = False


def fnum(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def load(path):
    return list(csv.DictReader(open(path)))


def write_csv(out, name, header, rows):
    p = out / f"{name}.csv"
    with p.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)
    return p


def agg_mean(rows, key_cols, val_col):
    groups = defaultdict(list)
    for r in rows:
        v = fnum(r.get(val_col))
        if v is not None:
            groups[tuple(r[k] for k in key_cols)].append(v)
    return {k: statistics.mean(v) for k, v in groups.items()}


def bar_png(out, name, labels, series, ylabel, title):
    if not HAVE_MPL:
        return
    import numpy as _np  # noqa
    x = range(len(labels))
    width = 0.8 / max(1, len(series))
    fig, ax = plt.subplots(figsize=(8, 5))
    for i, (sname, vals) in enumerate(series.items()):
        ax.bar([xi + i * width for xi in x], vals, width, label=sname)
    ax.set_xticks([xi + width * (len(series) - 1) / 2 for xi in x])
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out / f"{name}.png", dpi=140)
    plt.close(fig)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--long", default="results/summary/benchmark-long.csv")
    ap.add_argument("--out", default="reports/charts")
    args = ap.parse_args()
    repo = Path(__file__).resolve().parents[1]
    long_path = (repo / args.long) if not Path(args.long).is_absolute() else Path(args.long)
    out = (repo / args.out) if not Path(args.out).is_absolute() else Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    rows = load(long_path)
    models = sorted({r["model"] for r in rows})

    # 1) throughput prefill vs decode (blank, not the literal string "nan", when unmeasured —
    # e.g. TRT exposes no per-token inference metrics)
    pref = agg_mean(rows, ["model"], "prefill_tok_s")
    dec = agg_mean(rows, ["model"], "decode_tok_s")

    def _r2(x):
        return round(x, 2) if x is not None else ""
    write_csv(out, "fig_throughput", ["model", "prefill_tok_s", "decode_tok_s"],
              [[m, _r2(pref.get((m,))), _r2(dec.get((m,)))] for m in models])
    bar_png(out, "fig_throughput", models,
            {"prefill": [pref.get((m,), 0) for m in models], "decode": [dec.get((m,), 0) for m in models]},
            "tokens/s", "Prefill (compute-bound) vs Decode (bandwidth-bound)")

    # 2) energy per task by model+group
    en = agg_mean(rows, ["model", "layer", "track_or_task"], "energy_j")
    keys = sorted(en)
    write_csv(out, "fig_energy_per_task", ["model", "layer", "group", "energy_j_mean"],
              [[k[0], k[1], k[2], round(en[k], 2)] for k in keys])
    bar_png(out, "fig_energy_per_task", [f"{k[0]}/{k[1]}/{k[2]}" for k in keys],
            {"energy_J": [en[k] for k in keys]}, "Joules", "Mean energy per task")

    # 3) TTFT — M12: these are the MEAN of each run's own p50/p90/p99, which is NOT a percentile
    # of the pooled TTFT distribution (a mean of per-run percentiles has no percentile
    # interpretation). True pooled percentiles need per-request TTFT, which is not retained in the
    # summary. Columns are named `mean_of_run_pXX` to say exactly what they are, and n_runs is
    # reported so a 3-sample bar is not read as being as precise as a 29-sample one.
    p50 = agg_mean(rows, ["model"], "ttft_p50")
    p90 = agg_mean(rows, ["model"], "ttft_p90")
    p99 = agg_mean(rows, ["model"], "ttft_p99")
    n_ttft = {m: sum(1 for r in rows if r["model"] == m and fnum(r.get("ttft_p50")) is not None)
              for m in models}
    write_csv(out, "fig_ttft",
              ["model", "ttft_mean_of_run_p50", "ttft_mean_of_run_p90", "ttft_mean_of_run_p99", "n_runs"],
              [[m, p50.get((m,), ""), p90.get((m,), ""), p99.get((m,), ""), n_ttft[m]] for m in models])
    bar_png(out, "fig_ttft", models,
            {"mean p50": [p50.get((m,), 0) for m in models], "mean p90": [p90.get((m,), 0) for m in models],
             "mean p99": [p99.get((m,), 0) for m in models]}, "seconds",
            "TTFT (mean of per-run percentiles — see fig_ttft.csv note)")

    # 4) peak unified memory
    mem = agg_mean(rows, ["model", "layer", "track_or_task"], "unified_mem_peak_mib")
    mkeys = sorted(mem)
    write_csv(out, "fig_peak_memory", ["model", "layer", "group", "peak_mib"],
              [[k[0], k[1], k[2], round(mem[k], 1)] for k in mkeys])
    bar_png(out, "fig_peak_memory", [f"{k[0]}/{k[1]}/{k[2]}" for k in mkeys],
            {"peak_MiB": [mem[k] for k in mkeys]}, "MiB", "Peak unified memory")

    # 5) success/quality vs energy Pareto
    # quality = resolved (l1) or rubric_pass_rate (l2); x = energy_j (mean per model+group)
    # C3 fix: quality is averaged over the FULL denominator (every row with an outcome), NOT
    # only rows that also captured energy. Gating quality on energy-presence dropped the arms
    # with missing telemetry (nemotron's 8 metric-less L1 failures) and silently reintroduced
    # the survivorship bias aggregate-runs.py was fixed to prevent. Energy is paired only where
    # captured (energy_valid==1); the mean is blank when a group has no valid energy.
    pts = []
    qual = defaultdict(list)
    enr = defaultdict(list)
    for r in rows:
        q = fnum(r.get("resolved")) if r["layer"] == "l1" else fnum(r.get("rubric_pass_rate"))
        e = fnum(r.get("energy_j"))
        k = (r["model"], r["layer"], r["track_or_task"] if r["layer"] == "l2" else "all")
        if q is not None:
            qual[k].append(q)
        if e is not None:
            enr[k].append(e)
    for k in sorted(qual):
        e_mean = round(statistics.mean(enr[k]), 2) if enr[k] else ""
        pts.append([k[0], k[1], k[2], e_mean, round(statistics.mean(qual[k]), 4), len(qual[k])])
    write_csv(out, "fig_success_energy",
              ["model", "layer", "group", "energy_j_mean", "quality_mean", "n_quality"], pts)
    if HAVE_MPL and pts:
        fig, ax = plt.subplots(figsize=(7, 5))
        for row in pts:
            if row[3] == "":   # no valid energy captured for this group
                continue
            ax.scatter(row[3], row[4])
            ax.annotate(f"{row[0]}/{row[1]}", (row[3], row[4]), fontsize=8)
        ax.set_xlabel("energy per task (J)")
        ax.set_ylabel("quality (resolved / rubric pass-rate)")
        ax.set_title("Quality vs energy (Pareto)")
        fig.tight_layout()
        fig.savefig(out / "fig_success_energy.png", dpi=140)
        plt.close(fig)

    # ---- three-way efficiency / sparsity analysis (the paper's central cuts) ----
    # M11 fix: metrics are aggregated per (model, LAYER), never pooled across layers. Pooling
    # averaged L1 binary resolved-outcomes with L2 rubric fractions (and L3 pass@1) into one
    # "quality" number, and mixed per-task L1/L2 energy with whole-run L3 energy — so cross-model
    # deltas partly reflected which layers emitted metrics, not model differences.
    runtime_of = {r["model"]: r.get("runtime", "") for r in rows}

    def quality_of(r):
        if r["layer"] == "l1":
            return fnum(r.get("resolved"))
        if r["layer"] == "l2":
            return fnum(r.get("rubric_pass_rate"))
        return fnum(r.get("lcb_pass_at_1"))

    cols = ("quality", "tokens_per_joule", "j_per_gen_token", "decode_tok_s", "peak_mem",
            "active_params_b", "sparsity")
    pml = defaultdict(lambda: defaultdict(list))   # keyed by (model, layer)
    for r in rows:
        vals = {"quality": quality_of(r),
                "tokens_per_joule": fnum(r.get("tokens_per_joule")),
                "j_per_gen_token": fnum(r.get("j_per_gen_token")),
                "decode_tok_s": fnum(r.get("decode_tok_s")),
                "peak_mem": fnum(r.get("unified_mem_peak_mib")),
                "active_params_b": fnum(r.get("active_params_b")),
                "sparsity": fnum(r.get("sparsity_active_fraction"))}
        for c in cols:
            if vals[c] is not None:
                pml[(r["model"], r["layer"])][c].append(vals[c])
    pmean = {k: {c: (round(sum(v) / len(v), 4) if v else None) for c, v in d.items()}
             for k, d in pml.items()}
    keys = sorted(pmean)

    def cell(k, c):
        v = pmean.get(k, {}).get(c)
        return v if v is not None else ""

    # "efficiency despite lower success" table, one row per (model, layer). mem_util is dropped:
    # nvidia-smi memory-controller util reads N/A on GB10 unified memory, so it was never
    # measured. tokens/J is prompt-token-dominated (the agent loop re-sends context every turn,
    # ~99% of tokens are re-submitted prompt); j_per_gen_token is the decode-energy figure (M13).
    # Both energy columns are blank for TRT (nemotron), which exposes no per-token metrics.
    write_csv(out, "fig_efficiency_table",
              ["model", "runtime", "layer", "success_or_quality", "n", "decode_tok_s",
               "tokens_per_joule", "j_per_gen_token", "peak_mem_mib", "active_params_b", "sparsity"],
              [[k[0], runtime_of.get(k[0], ""), k[1], cell(k, "quality"),
                len(pml[k].get("quality", [])), cell(k, "decode_tok_s"),
                cell(k, "tokens_per_joule"), cell(k, "j_per_gen_token"), cell(k, "peak_mem"),
                cell(k, "active_params_b"), cell(k, "sparsity")] for k in keys])

    # success-vs-efficiency Pareto (quality vs tokens/joule), one point per (model, layer) —
    # both axes are layer-dependent, so a single per-model point would itself be a pooling.
    write_csv(out, "fig_pareto_efficiency", ["model", "layer", "tokens_per_joule", "quality"],
              [[k[0], k[1], cell(k, "tokens_per_joule"), cell(k, "quality")] for k in keys])
    if HAVE_MPL:
        fig, ax = plt.subplots(figsize=(7, 5))
        for k in keys:
            x, y = pmean[k].get("tokens_per_joule"), pmean[k].get("quality")
            if x is not None and y is not None:
                ax.scatter(x, y); ax.annotate(f"{k[0]}/{k[1]}", (x, y), fontsize=8)
        ax.set_xlabel("tokens / joule (efficiency)"); ax.set_ylabel("success / rubric quality")
        ax.set_title("Success vs efficiency Pareto (per model/layer)"); fig.tight_layout()
        fig.savefig(out / "fig_pareto_efficiency.png", dpi=140); plt.close(fig)

    # sparsity vs decode: does higher sparsity relieve the bandwidth bottleneck? decode_tok_s is
    # a serving-throughput property; reported per (model, layer) to avoid cross-layer pooling.
    write_csv(out, "fig_sparsity_decode",
              ["model", "layer", "active_params_b", "sparsity", "decode_tok_s"],
              [[k[0], k[1], cell(k, "active_params_b"), cell(k, "sparsity"),
                cell(k, "decode_tok_s")] for k in keys])
    if HAVE_MPL:
        fig, ax = plt.subplots(figsize=(7, 5))
        for k in keys:
            x, y = pmean[k].get("active_params_b"), pmean[k].get("decode_tok_s")
            if x is not None and y is not None:
                ax.scatter(x, y); ax.annotate(f"{k[0]}/{k[1]}", (x, y), fontsize=8)
        ax.set_xlabel("active params (B)"); ax.set_ylabel("decode tokens/s")
        ax.set_title("Sparse-activation decode: throughput vs active params"); fig.tight_layout()
        fig.savefig(out / "fig_sparsity_decode.png", dpi=140); plt.close(fig)

    print(f"[figures] wrote data CSVs to {out}" + ("" if HAVE_MPL else "  (matplotlib not installed → PNGs skipped)"))


if __name__ == "__main__":
    main()
